version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "todos"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  todo_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      SECRET: "bemovil"
      NODE_ENV: "development"
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: todos
    depends_on:
      - db

volumes:
  my-db:
